# Generated by Django 5.2.5 on 2025-10-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo Promocion',
                'verbose_name_plural': 'Tipo de promociones',
                'db_table': 'tipo_promocion',
            },
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promocion', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='codigo_promocional',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='descuento_monto',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='descuento_porcentaje',
        ),
        migrations.AlterModelTable(
            name='promocion',
            table='promocion',
        ),
        migrations.CreateModel(
            name='ProductoPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion2.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion2.promocion')),
            ],
            options={
                'verbose_name': 'Producto en promoción',
                'verbose_name_plural': 'Productos en promoción',
                'db_table': 'producto_promocion',
            },
        ),
        migrations.CreateModel(
            name='DetallePromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_promocional', models.CharField(blank=True, max_length=20, null=True)),
                ('condicion', models.TextField(blank=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion2.promocion')),
                ('tipo_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion2.tipodescuento')),
            ],
            options={
                'verbose_name': 'Detalle promocion',
                'verbose_name_plural': 'Detalle promociones',
                'db_table': 'detalle_promocion',
            },
        ),
    ]
