# Generated by Django 4.2.26 on 2025-11-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion2', '0002_producto_tipodescuento_alter_promocion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='usos',
            field=models.IntegerField(default=0),
        ),
    ]
