# Generated by Django 4.2.26 on 2025-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion2', '0003_promocion_usos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepromocion',
            name='valor_descuento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
