# Generated by Django 4.2.26 on 2025-12-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion2', '0004_alter_detallepromocion_valor_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopromocion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productopromocion',
            name='promocion',
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AddField(
            model_name='promocion',
            name='codigo_promocional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_descuento',
            field=models.CharField(choices=[('porcentual', 'Porcentual'), ('dinero', 'Resta en dinero')], default='porcentual', max_length=10),
        ),
        migrations.AddField(
            model_name='promocion',
            name='valor_descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DetallePromocion',
        ),
        migrations.DeleteModel(
            name='ProductoPromocion',
        ),
        migrations.DeleteModel(
            name='TipoDescuento',
        ),
    ]
