# Generated by Django 5.2.5 on 2025-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'clientes',
                'db_table': 'Cliente',
            },
        ),
    ]
