# Generated by Django 5.2.5 on 2025-10-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntos', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='aplicacion.cliente')),
            ],
            options={
                'verbose_name': 'Movimiento puntos',
                'verbose_name_plural': 'Movimientos Puntos',
                'db_table': 'movimiento_puntos',
            },
        ),
    ]
