# Generated by Django 4.2.26 on 2025-11-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_movimientopuntos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='movimientopuntos',
            options={'managed': False, 'verbose_name': 'Movimiento puntos', 'verbose_name_plural': 'Movimientos Puntos'},
        ),
    ]
