# Generated by Django 4.2.26 on 2025-11-26 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion2', '0003_promocion_usos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0004_alter_cliente_options_alter_movimientopuntos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.CreateModel(
            name='ReportePromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion2.promocion', verbose_name='Promoción asociada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que generó el reporte')),
            ],
        ),
    ]
